/**
 * The action types.
 * @type {Object(String)}
 */
const TYPE = {
  CYCLE_SCOPE      : 'ACTION_TYPE_CYCLE_SCOPE',
  DISABLE          : 'ACTION_TYPE_DISABLE',
  ENABLE           : 'ACTION_TYPE_ENABLE',
  INITIALIZE       : 'ACTION_TYPE_INITIALIZE',
  SELECT           : 'ACTION_TYPE_SELECT',
  SELECT_IN_PERIOD : 'ACTION_TYPE_SELECT_IN_PERIOD',
  SET_FIRST_DAY    : 'ACTION_TYPE_SET_FIRST_DAY',
  SET_LANGUAGE     : 'ACTION_TYPE_SET_LANGUAGE',
}



module.exports = {
  TYPE,
}
