/*!
 * Legacy browser support
 */
Array.isArray||(Array.isArray=function(e){return"[object Array]"=={}.toString.call(e)}),[].map||(Array.prototype.map=function(e,t){for(var n=this,i=n.length,o=Array(i),r=0;i>r;r++)r in n&&(o[r]=e.call(t,n[r],r,n));return o}),[].filter||(Array.prototype.filter=function(e){if(null==this)throw new TypeError;var t=Object(this),n=t.length>>>0;if("function"!=typeof e)throw new TypeError;for(var i=[],o=arguments[1],r=0;n>r;r++)if(r in t){var a=t[r];e.call(o,a,r,t)&&i.push(a)}return i}),[].indexOf||(Array.prototype.indexOf=function(e){if(null==this)throw new TypeError;var t=Object(this),n=t.length>>>0;if(0===n)return-1;var i=0;if(arguments.length>1&&(i=Number(arguments[1]),i!=i?i=0:0!==i&&1/0!=i&&i!=-1/0&&(i=(i>0||-1)*Math.floor(Math.abs(i)))),i>=n)return-1;for(var o=i>=0?i:Math.max(n-Math.abs(i),0);n>o;o++)if(o in t&&t[o]===e)return o;return-1});/*!
 * Cross-Browser Split 1.1.1
 * Copyright 2007-2012 Steven Levithan <stevenlevithan.com>
 * Available under the MIT License
 * http://blog.stevenlevithan.com/archives/cross-browser-split
 */
var nativeSplit=String.prototype.split,compliantExecNpcg=void 0===/()??/.exec("")[1];String.prototype.split=function(e,t){var n=this;if("[object RegExp]"!==Object.prototype.toString.call(e))return nativeSplit.call(n,e,t);var i,o,r,a,s=[],l=(e.ignoreCase?"i":"")+(e.multiline?"m":"")+(e.extended?"x":"")+(e.sticky?"y":""),u=0;for(e=RegExp(e.source,l+"g"),n+="",compliantExecNpcg||(i=RegExp("^"+e.source+"$(?!\\s)",l)),t=void 0===t?-1>>>0:t>>>0;(o=e.exec(n))&&(r=o.index+o[0].length,!(r>u&&(s.push(n.slice(u,o.index)),!compliantExecNpcg&&o.length>1&&o[0].replace(i,function(){for(var e=1;arguments.length-2>e;e++)void 0===arguments[e]&&(o[e]=void 0)}),o.length>1&&o.index<n.length&&Array.prototype.push.apply(s,o.slice(1)),a=o[0].length,u=r,s.length>=t)));)e.lastIndex===o.index&&e.lastIndex++;return u===n.length?(a||!e.test(""))&&s.push(""):s.push(n.slice(u)),s.length>t?s.slice(0,t):s};