/*!
 * Legacy browser support
 */
Array.isArray||(Array.isArray=function(t){return"[object Array]"=={}.toString.call(t)}),[].map||(Array.prototype.map=function(t,e){for(var n=this,i=n.length,o=Array(i),r=0;i>r;r++)r in n&&(o[r]=t.call(e,n[r],r,n));return o}),[].filter||(Array.prototype.filter=function(t){if(null==this)throw new TypeError;var e=Object(this),n=e.length>>>0;if("function"!=typeof t)throw new TypeError;for(var i=[],o=arguments[1],r=0;n>r;r++)if(r in e){var a=e[r];t.call(o,a,r,e)&&i.push(a)}return i}),[].indexOf||(Array.prototype.indexOf=function(t){if(null==this)throw new TypeError;var e=Object(this),n=e.length>>>0;if(0===n)return-1;var i=0;if(arguments.length>1&&(i=Number(arguments[1]),i!=i?i=0:0!==i&&1/0!=i&&i!=-1/0&&(i=(i>0||-1)*Math.floor(Math.abs(i)))),i>=n)return-1;for(var o=i>=0?i:Math.max(n-Math.abs(i),0);n>o;o++)if(o in e&&e[o]===t)return o;return-1});/*!
 * Cross-Browser Split 1.1.1
 * Copyright 2007-2012 Steven Levithan <stevenlevithan.com>
 * Available under the MIT License
 * http://blog.stevenlevithan.com/archives/cross-browser-split
 */
var nativeSplit=String.prototype.split,compliantExecNpcg=void 0===/()??/.exec("")[1];String.prototype.split=function(t,e){var n=this;if("[object RegExp]"!==Object.prototype.toString.call(t))return nativeSplit.call(n,t,e);var i,o,r,a,s=[],l=(t.ignoreCase?"i":"")+(t.multiline?"m":"")+(t.extended?"x":"")+(t.sticky?"y":""),u=0;for(t=RegExp(t.source,l+"g"),n+="",compliantExecNpcg||(i=RegExp("^"+t.source+"$(?!\\s)",l)),e=void 0===e?-1>>>0:e>>>0;(o=t.exec(n))&&(r=o.index+o[0].length,!(r>u&&(s.push(n.slice(u,o.index)),!compliantExecNpcg&&o.length>1&&o[0].replace(i,function(){for(var t=1;arguments.length-2>t;t++)void 0===arguments[t]&&(o[t]=void 0)}),o.length>1&&o.index<n.length&&Array.prototype.push.apply(s,o.slice(1)),a=o[0].length,u=r,s.length>=e)));)t.lastIndex===o.index&&t.lastIndex++;return u===n.length?(a||!t.test(""))&&s.push(""):s.push(n.slice(u)),s.length>e?s.slice(0,e):s};